# ===============================================
# User Management Service - Docker Compose
# ===============================================
# Simplified development environment using Supabase

services:
  # ====================================
  # User Management Service
  # ====================================
  user-management:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: nutrifit-user-management-dev
    ports:
      - "8001:8001"
    environment:
      - ENVIRONMENT=development
      - DEBUG=true
      - LOG_LEVEL=DEBUG
      - DATABASE_SCHEMA=user_management
      
      # Supabase Configuration (from .env)
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
      
      # Security
      - SECRET_KEY=${SECRET_KEY:-dev-secret-key-change-in-production}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY:-dev-jwt-secret}
      - JWT_ALGORITHM=HS256
      - JWT_ACCESS_TOKEN_EXPIRE_MINUTES=60
      - JWT_REFRESH_TOKEN_EXPIRE_DAYS=30
      
      # CORS
      - ALLOWED_ORIGINS=http://localhost:3000,capacitor://localhost,https://localhost,http://localhost:8080
      
      # Features
      - ENABLE_REAL_TIME=true
      - ENABLE_AUTH=true
      - ENABLE_STORAGE=false
      
      # Performance
      - RATE_LIMIT_REQUESTS_PER_MINUTE=60
      - REQUEST_TIMEOUT_SECONDS=30
      - MAX_CONNECTIONS=100
      
      # Monitoring (optional for development)
      - SENTRY_DSN=${SENTRY_DSN:-}
      - STRUCTURED_LOGGING=true
      
    volumes:
      - ./:/app
      - /app/.venv  # Exclude venv from volume mount
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

# ====================================
# Development Commands
# ====================================
# Usage examples:
#
# Start development environment:
#   docker-compose up -d
#
# View logs:
#   docker-compose logs -f user-management
#
# Run tests:
#   docker-compose exec user-management poetry run pytest
#
# Access shell:
#   docker-compose exec user-management bash
#
# Rebuild after changes:
#   docker-compose up --build
#
# Stop and clean:
#   docker-compose down
#
# NOTE: This configuration uses Supabase for all database needs.
# No local PostgreSQL or Redis containers are needed.
