# 🚀 GraphQL Gateway v0.2.0 - Render.com Configuration
# Following User Management Service deployment playbook

services:
  - type: web
    name: gymbro-graphql-gateway
    runtime: docker
    dockerfilePath: ./services/graphql-gateway/Dockerfile.minimal
    # ✅ LESSON LEARNED: Health check path is critical
    healthCheckPath: /health
    # ✅ LESSON LEARNED: Auto-deploy from main branch
    autoDeploy: true
    branch: main
    # ✅ Free tier resources
    plan: free
    # ✅ Environment variables following deployment lessons
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        generateValue: true # Render auto-assigns port
    # ✅ LESSON LEARNED: Build commands for Docker
    buildCommand: echo "Using Docker build"
    # Docker images don't need start command
