# 🚀 GraphQL Gateway v0.2.0 - Render.com Configuration
# Following User Management Service deployment playbook

services:
  - type: web
    name: gymbro-graphql-gateway
    runtime: docker
    dockerfilePath: ./services/graphql-gateway/Dockerfile
    # ✅ Apollo Gateway with Federation
    healthCheckPath: /health
    # ✅ LESSON LEARNED: Auto-deploy from main branch
    autoDeploy: true
    branch: main
    # ✅ Free tier resources
    plan: free
    # ✅ Environment variables following deployment lessons
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        generateValue: true # Render auto-assigns port
      - key: USER_MANAGEMENT_URL
        value: https://gymbro-user-service.onrender.com/graphql
      - key: CORS_ORIGINS
        value: "*" # Permissive for MVP debug
      - key: FORCE_FULL_SERVER
        value: "true" # Force full Apollo Server (not minimal)
      - key: CACHE_BUST
        value: "2025-08-16-cleanup" # Force rebuild after cleanup
    # ✅ LESSON LEARNED: Build commands for Docker
    buildCommand: echo "Using Docker build"
    # Docker images don't need start command
